on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dockercontregrf.azurecr.io
        username: ${{ secrets.acr_dockercontregrf_username }}
        password: ${{ secrets.acr_dockercontregrf_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t dockercontregrf.azurecr.io/appregrf:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push dockercontregrf.azurecr.io/appregrf:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_appregrf_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep appregrf8867 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace appregrf8867`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: appregrf8867
        container-registry-url: dockercontregrf.azurecr.io
        container-registry-username: ${{ secrets.acr_dockercontregrf_username }}
        container-registry-password: ${{ secrets.acr_dockercontregrf_password }}
        secret-name: appregrfdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: appregrf8867
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          dockercontregrf.azurecr.io/appregrf:${{ github.sha }}
        imagepullsecrets: |
          appregrfdockerauth
